// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhM9KsPnmEYD_dhMadckr9dSorb8tB2UI',
    appId: '1:198007555962:web:229b127c5f09d6177338c3',
    messagingSenderId: '198007555962',
    projectId: 'schoolapp-14690',
    authDomain: 'schoolapp-14690.firebaseapp.com',
    storageBucket: 'schoolapp-14690.firebasestorage.app',
    measurementId: 'G-TQLWQYCKTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD030M_vLq1dJYR8FPdnVMPUGiv2GGpVyo',
    appId: '1:198007555962:android:2f3ec45d12e29e4d7338c3',
    messagingSenderId: '198007555962',
    projectId: 'schoolapp-14690',
    storageBucket: 'schoolapp-14690.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgpASdlLPwaRr7riygY_AotBRNpKF1Hjg',
    appId: '1:198007555962:ios:899d2870a787028c7338c3',
    messagingSenderId: '198007555962',
    projectId: 'schoolapp-14690',
    storageBucket: 'schoolapp-14690.firebasestorage.app',
    iosBundleId: 'com.example.schoolapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgpASdlLPwaRr7riygY_AotBRNpKF1Hjg',
    appId: '1:198007555962:ios:5a40d90f584b88037338c3',
    messagingSenderId: '198007555962',
    projectId: 'schoolapp-14690',
    storageBucket: 'schoolapp-14690.firebasestorage.app',
    iosBundleId: 'com.jupitus.schoolapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhM9KsPnmEYD_dhMadckr9dSorb8tB2UI',
    appId: '1:198007555962:web:bfcaea2b39780b407338c3',
    messagingSenderId: '198007555962',
    projectId: 'schoolapp-14690',
    authDomain: 'schoolapp-14690.firebaseapp.com',
    storageBucket: 'schoolapp-14690.firebasestorage.app',
    measurementId: 'G-KGYWXKTZ4Y',
  );

}